english2hebrew = {
    'Alef': 'א',
    'Bet': 'ב',
    'Gimel': 'ג',
    'Dalet': 'ד',
    'He': 'ה',
    'Vav': 'ו',
    'Zayin': 'ז',
    'Het': 'ח',
    'Tet': 'ט',
    'Yod': 'י',
    'Kaf': 'כ',
    'Lamed': 'ל',
    'Mem': 'מ',
    'Nun': 'נ',
    'Samech': 'ס',
    'Ayin': 'ע',
    'Peh': 'פ',
    'Tsadeh': 'צ',
    'Qof': 'ק',
    'Resh': 'ר',
    'Shin': 'ש',
    'Tav': 'ת',
}
