runtime: nodejs20

env_variables:
  NODE_ENV: 'production'

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html

  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2
